window.esdocSearchIndex = [
  [
    "@graph-data-structure/specification/src/implementation/abstractdirectedgraph.js~abstractdirectedgraph",
    "class/src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph.html",
    "<span>AbstractDirectedGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/AbstractDirectedGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/abstractgraph.js~abstractgraph",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html",
    "<span>AbstractGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/AbstractGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/abstractundirectedgraph.js~abstractundirectedgraph",
    "class/src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph.html",
    "<span>AbstractUndirectedGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/AbstractUndirectedGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/directedgraph.js~directedgraph",
    "class/src/implementation/DirectedGraph.js~DirectedGraph.html",
    "<span>DirectedGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/DirectedGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/directedmultigraph.js~directedmultigraph",
    "class/src/implementation/DirectedMultiGraph.js~DirectedMultiGraph.html",
    "<span>DirectedMultiGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/DirectedMultiGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/graph.js~graph",
    "class/src/implementation/Graph.js~Graph.html",
    "<span>Graph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/Graph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/undirectedgraph.js~undirectedgraph",
    "class/src/implementation/UndirectedGraph.js~UndirectedGraph.html",
    "<span>UndirectedGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/UndirectedGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/implementation/undirectedmultigraph.js~undirectedmultigraph",
    "class/src/implementation/UndirectedMultiGraph.js~UndirectedMultiGraph.html",
    "<span>UndirectedMultiGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/implementation/UndirectedMultiGraph.js</span>",
    "class"
  ],
  [
    "@graph-data-structure/specification/src/spec/digraph.js~digraph",
    "function/index.html#static-function-digraph",
    "<span>digraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/spec/digraph.js</span>",
    "function"
  ],
  [
    "@graph-data-structure/specification/src/spec/graph.js~graph",
    "function/index.html#static-function-graph",
    "<span>graph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/spec/graph.js</span>",
    "function"
  ],
  [
    "@graph-data-structure/specification/src/spec/methods.js~methods",
    "function/index.html#static-function-methods",
    "<span>methods</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/spec/methods.js</span>",
    "function"
  ],
  [
    "@graph-data-structure/specification/src/spec/multidigraph.js~multidigraph",
    "function/index.html#static-function-multiDigraph",
    "<span>multiDigraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/spec/multiDigraph.js</span>",
    "function"
  ],
  [
    "@graph-data-structure/specification/src/spec/multigraph.js~multigraph",
    "function/index.html#static-function-multiGraph",
    "<span>multiGraph</span> <span class=\"search-result-import-path\">@graph-data-structure/specification/src/spec/multiGraph.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/implementation/abstractdirectedgraph.js",
    "file/src/implementation/AbstractDirectedGraph.js.html",
    "src/implementation/AbstractDirectedGraph.js",
    "file"
  ],
  [
    "src/implementation/abstractdirectedgraph.js~abstractdirectedgraph#e",
    "class/src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph.html#instance-member-E",
    "src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph#E",
    "member"
  ],
  [
    "src/implementation/abstractdirectedgraph.js~abstractdirectedgraph#initr",
    "class/src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph.html#instance-method-initr",
    "src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph#initr",
    "method"
  ],
  [
    "src/implementation/abstractdirectedgraph.js~abstractdirectedgraph#outitr",
    "class/src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph.html#instance-method-outitr",
    "src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph#outitr",
    "method"
  ],
  [
    "src/implementation/abstractdirectedgraph.js~abstractdirectedgraph#reverse",
    "class/src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph.html#instance-method-reverse",
    "src/implementation/AbstractDirectedGraph.js~AbstractDirectedGraph#reverse",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js",
    "file/src/implementation/AbstractGraph.js.html",
    "src/implementation/AbstractGraph.js",
    "file"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#dpitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-dpitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#dpitr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#dsitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-dsitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#dsitr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#eadd",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-eadd",
    "src/implementation/AbstractGraph.js~AbstractGraph#eadd",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#edel",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-edel",
    "src/implementation/AbstractGraph.js~AbstractGraph#edel",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#edges",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-edges",
    "src/implementation/AbstractGraph.js~AbstractGraph#edges",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#eitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-eitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#eitr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#endpoints",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-endpoints",
    "src/implementation/AbstractGraph.js~AbstractGraph#endpoints",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#iitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-iitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#iitr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#incident",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-incident",
    "src/implementation/AbstractGraph.js~AbstractGraph#incident",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#ingoing",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-ingoing",
    "src/implementation/AbstractGraph.js~AbstractGraph#ingoing",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#initr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-initr",
    "src/implementation/AbstractGraph.js~AbstractGraph#initr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#nitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-nitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#nitr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#outgoing",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-outgoing",
    "src/implementation/AbstractGraph.js~AbstractGraph#outgoing",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#outitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-outitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#outitr",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#reverse",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-reverse",
    "src/implementation/AbstractGraph.js~AbstractGraph#reverse",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#vadd",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-vadd",
    "src/implementation/AbstractGraph.js~AbstractGraph#vadd",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#vdel",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-vdel",
    "src/implementation/AbstractGraph.js~AbstractGraph#vdel",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#vertices",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-vertices",
    "src/implementation/AbstractGraph.js~AbstractGraph#vertices",
    "method"
  ],
  [
    "src/implementation/abstractgraph.js~abstractgraph#vitr",
    "class/src/implementation/AbstractGraph.js~AbstractGraph.html#instance-method-vitr",
    "src/implementation/AbstractGraph.js~AbstractGraph#vitr",
    "method"
  ],
  [
    "src/implementation/abstractundirectedgraph.js",
    "file/src/implementation/AbstractUndirectedGraph.js.html",
    "src/implementation/AbstractUndirectedGraph.js",
    "file"
  ],
  [
    "src/implementation/abstractundirectedgraph.js~abstractundirectedgraph#initr",
    "class/src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph.html#instance-method-initr",
    "src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph#initr",
    "method"
  ],
  [
    "src/implementation/abstractundirectedgraph.js~abstractundirectedgraph#outitr",
    "class/src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph.html#instance-method-outitr",
    "src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph#outitr",
    "method"
  ],
  [
    "src/implementation/abstractundirectedgraph.js~abstractundirectedgraph#reverse",
    "class/src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph.html#instance-method-reverse",
    "src/implementation/AbstractUndirectedGraph.js~AbstractUndirectedGraph#reverse",
    "method"
  ],
  [
    "src/implementation/directedgraph.js",
    "file/src/implementation/DirectedGraph.js.html",
    "src/implementation/DirectedGraph.js",
    "file"
  ],
  [
    "src/implementation/directedgraph.js~directedgraph#eadd",
    "class/src/implementation/DirectedGraph.js~DirectedGraph.html#instance-method-eadd",
    "src/implementation/DirectedGraph.js~DirectedGraph#eadd",
    "method"
  ],
  [
    "src/implementation/directedmultigraph.js",
    "file/src/implementation/DirectedMultiGraph.js.html",
    "src/implementation/DirectedMultiGraph.js",
    "file"
  ],
  [
    "src/implementation/graph.js",
    "file/src/implementation/Graph.js.html",
    "src/implementation/Graph.js",
    "file"
  ],
  [
    "src/implementation/graph.js~graph#e",
    "class/src/implementation/Graph.js~Graph.html#instance-member-E",
    "src/implementation/Graph.js~Graph#E",
    "member"
  ],
  [
    "src/implementation/graph.js~graph#v",
    "class/src/implementation/Graph.js~Graph.html#instance-member-V",
    "src/implementation/Graph.js~Graph#V",
    "member"
  ],
  [
    "src/implementation/graph.js~graph#constructor",
    "class/src/implementation/Graph.js~Graph.html#instance-constructor-constructor",
    "src/implementation/Graph.js~Graph#constructor",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#eadd",
    "class/src/implementation/Graph.js~Graph.html#instance-method-eadd",
    "src/implementation/Graph.js~Graph#eadd",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#edel",
    "class/src/implementation/Graph.js~Graph.html#instance-method-edel",
    "src/implementation/Graph.js~Graph#edel",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#eitr",
    "class/src/implementation/Graph.js~Graph.html#instance-method-eitr",
    "src/implementation/Graph.js~Graph#eitr",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#endpoints",
    "class/src/implementation/Graph.js~Graph.html#instance-method-endpoints",
    "src/implementation/Graph.js~Graph#endpoints",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#vadd",
    "class/src/implementation/Graph.js~Graph.html#instance-method-vadd",
    "src/implementation/Graph.js~Graph#vadd",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#vdel",
    "class/src/implementation/Graph.js~Graph.html#instance-method-vdel",
    "src/implementation/Graph.js~Graph#vdel",
    "method"
  ],
  [
    "src/implementation/graph.js~graph#vitr",
    "class/src/implementation/Graph.js~Graph.html#instance-method-vitr",
    "src/implementation/Graph.js~Graph#vitr",
    "method"
  ],
  [
    "src/implementation/undirectedgraph.js",
    "file/src/implementation/UndirectedGraph.js.html",
    "src/implementation/UndirectedGraph.js",
    "file"
  ],
  [
    "src/implementation/undirectedgraph.js~undirectedgraph#eadd",
    "class/src/implementation/UndirectedGraph.js~UndirectedGraph.html#instance-method-eadd",
    "src/implementation/UndirectedGraph.js~UndirectedGraph#eadd",
    "method"
  ],
  [
    "src/implementation/undirectedmultigraph.js",
    "file/src/implementation/UndirectedMultiGraph.js.html",
    "src/implementation/UndirectedMultiGraph.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/spec/digraph.js",
    "file/src/spec/digraph.js.html",
    "src/spec/digraph.js",
    "file"
  ],
  [
    "src/spec/graph.js",
    "file/src/spec/graph.js.html",
    "src/spec/graph.js",
    "file"
  ],
  [
    "src/spec/methods.js",
    "file/src/spec/methods.js.html",
    "src/spec/methods.js",
    "file"
  ],
  [
    "src/spec/multidigraph.js",
    "file/src/spec/multiDigraph.js.html",
    "src/spec/multiDigraph.js",
    "file"
  ],
  [
    "src/spec/multigraph.js",
    "file/src/spec/multiGraph.js.html",
    "src/spec/multiGraph.js",
    "file"
  ]
]